### ISSUE TITLE
The dropdown on what subject interests you does not close on second click?

### ISSUE THREAD

**Issue by gopherine** [evaristoc/fCC_R3#15]
The drop down on the  main page doesnt close after the selection has been made. I feel the dropdown should work as below : 

- [ ]  It should either close after the selection is made or after doubleclick

- [ ]  If it has to be visible and waits for second click then , the user should be able to make a second call

**Comment by evaristoc** [comment]
"It should either close after the selection is made or after doubleclick"

This is more like the expected behaviour. I would prefer the final selection to shown. Also, the person should be able to reopen if required.

The person can select ONLY ONE of the subjects listed in the drop down list (this is a **User Story** so it shouldn't change)

**Comment by gopherine** [comment]
i believe even after he goes to user story and the drop down is visbile then still it should allow the user to modify its selection there is some issue with mutidropdown in angular i would rather prefer material or bootstraps default drop down stuff for the same ... i am trying to use material for the fix

**Comment by evaristoc** [comment]
Ok, @atharvajava let's see it? Just try to keep much of the design by @sandra-dudley unchanged? Her work should be the base of further developments.
