### ISSUE TITLE
Loading of the selection filters in search form

### ISSUE THREAD

**Issue by sandra-dudley** [evaristoc/fCC_R3#2]
There is a lapse of time between the time the page loads and the database loads, so the selections are empty for a while. 

Should the search form appear after a delay or after the database is loaded? Or just write loading first?

**Comment by evaristoc** [comment]
@atharvajava

you have some propositions for this part?

**Comment by gopherine** [comment]
i am thinking of instead of dynamically populating the list from database we should statically put values here thats 1 till the time firebase is being loaded once the user select in one of the options the page should show the user loading sign as if its loading the contents since the time lapse is not too much i believe this would work pretty well

**Comment by evaristoc** [comment]
The only issue would be that if the subjects change, then there won't be automatic update. In my opinion, both solutions are fine. I would say: let's take the simplest route? The project is a PoC at the moment.

**Comment by evaristoc** [comment]
It is not a priority.
